name: 'jukebox'
version: '1.0.0'
config-version: 2
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  jukebox:
    marts:
      dimensions:
        +materialized: table
        +schema: dimensions
      facts:
        +materialized: table
        +schema: facts
      analytics:
        +materialized: table
        +schema: analytics
    staging:
      +materialized: view
      +schema: staging
    

seeds:
  jukebox:
    +schema: staging
    device_id_mapping:
      +column_types:
        old_device_id: varchar
        new_device_id: varchar