default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: [MT10129.eu-west-2.aws]
      user: [adminrenne]
      password: [Renne2005!]
      role: PC_DBT_ROLE
      database: PC_DBT_DB
      warehouse: [Transforming]
      schema: DBT_RBOTCHWAY_STAGING

